/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustedBrowserRouteImport } from './routes/trusted-browser'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'

const TrustedBrowserRoute = TrustedBrowserRouteImport.update({
  id: '/trusted-browser',
  path: '/trusted-browser',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OpportunitiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/eligibility': typeof EligibilityRoute
  '/notifications': typeof NotificationsRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/trusted-browser': typeof TrustedBrowserRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/eligibility': typeof EligibilityRoute
  '/notifications': typeof NotificationsRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/trusted-browser': typeof TrustedBrowserRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/eligibility': typeof EligibilityRoute
  '/notifications': typeof NotificationsRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/trusted-browser': typeof TrustedBrowserRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/eligibility'
    | '/notifications'
    | '/opportunities'
    | '/trusted-browser'
    | '/opportunities/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/eligibility'
    | '/notifications'
    | '/opportunities'
    | '/trusted-browser'
    | '/opportunities/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/eligibility'
    | '/notifications'
    | '/opportunities'
    | '/trusted-browser'
    | '/opportunities/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  EligibilityRoute: typeof EligibilityRoute
  NotificationsRoute: typeof NotificationsRoute
  OpportunitiesRoute: typeof OpportunitiesRouteWithChildren
  TrustedBrowserRoute: typeof TrustedBrowserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trusted-browser': {
      id: '/trusted-browser'
      path: '/trusted-browser'
      fullPath: '/trusted-browser'
      preLoaderRoute: typeof TrustedBrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
  }
}

interface OpportunitiesRouteChildren {
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
}

const OpportunitiesRouteChildren: OpportunitiesRouteChildren = {
  OpportunitiesIdRoute: OpportunitiesIdRoute,
}

const OpportunitiesRouteWithChildren = OpportunitiesRoute._addFileChildren(
  OpportunitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  EligibilityRoute: EligibilityRoute,
  NotificationsRoute: NotificationsRoute,
  OpportunitiesRoute: OpportunitiesRouteWithChildren,
  TrustedBrowserRoute: TrustedBrowserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
